# Generated by Django 5.2.5 on 2025-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cliente_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
    ]
