# Generated by Django 5.2.5 on 2025-09-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_exercicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='categoria',
            field=models.IntegerField(null=True),
        ),
    ]
