# Generated by Django 5.2.5 on 2025-09-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_exercicios_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoriatreino'),
        ),
    ]
