# Generated by Django 5.2.5 on 2025-09-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_exercicios_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatreino',
            name='grupo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
