# Generated by Django 5.2.5 on 2025-09-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_categoriatreino_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatreino',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagens/'),
        ),
    ]
