# Generated by Django 5.2.5 on 2025-09-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_categoriatreino_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatreino',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/imagens/'),
        ),
    ]
