# Generated by Django 5.2.5 on 2025-09-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_categoriatreino_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatreino',
            name='imagem',
            field=models.FileField(null=True, upload_to='imagens'),
        ),
    ]
