# Generated by Django 5.2.5 on 2025-09-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_categoriatreino_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicios',
            name='imagem',
            field=models.FileField(null=True, upload_to='imagens'),
        ),
    ]
