# Generated by Django 5.2.5 on 2025-09-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cliente_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(null=True)),
                ('vencimento', models.DateField(null=True)),
            ],
        ),
    ]
