# Generated by Django 5.2.5 on 2025-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_receber'),
    ]

    operations = [
        migrations.AddField(
            model_name='receber',
            name='pagamento',
            field=models.FloatField(null=True),
        ),
    ]
