# Generated by Django 5.2.5 on 2025-09-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_receber_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receber',
            name='pagamento',
            field=models.DateField(null=True),
        ),
    ]
