# Generated by Django 5.2.5 on 2025-09-18 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_receber_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(null=True)),
                ('data_final', models.DateField(null=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='treinoSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('id_treino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.treino')),
            ],
        ),
        migrations.CreateModel(
            name='exercicioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=255)),
                ('series', models.IntegerField(null=True)),
                ('repeticoes', models.IntegerField(null=True)),
                ('observacao', models.CharField(max_length=500)),
                ('id_dia_semana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.treinosemana')),
            ],
        ),
    ]
