# Generated by Django 5.2.5 on 2025-09-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_treino_treinosemana_exerciciodia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciciodia',
            old_name='id_dia_semana',
            new_name='dia_semana',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='treinosemana',
            old_name='id_treino',
            new_name='treino',
        ),
    ]
