# Generated by Django 5.2.5 on 2025-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_id_dia_semana_exerciciodia_dia_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciciodia',
            name='imagem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
