# Generated by Django 5.2.5 on 2025-09-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_exerciciodia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciodia',
            name='observacao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
