# Generated by Django 5.2.5 on 2025-10-03 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_exerciciodia_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(auto_created=True, null=True)),
                ('peso', models.FloatField(null=True)),
                ('altura', models.FloatField(null=True)),
                ('pescoco', models.FloatField(null=True)),
                ('peitoral', models.FloatField(null=True)),
                ('braco_d', models.FloatField(null=True)),
                ('braco_e', models.FloatField(null=True)),
                ('cintura', models.FloatField(null=True)),
                ('abdomen', models.FloatField(null=True)),
                ('quadril', models.FloatField(null=True)),
                ('coxa_d', models.FloatField(null=True)),
                ('coxa_e', models.FloatField(null=True)),
                ('pantu_d', models.FloatField(null=True)),
                ('pantu_e', models.FloatField(null=True)),
                ('triceps', models.FloatField(null=True)),
                ('subescapular', models.FloatField(null=True)),
                ('axiliar_media', models.FloatField(null=True)),
                ('peito', models.FloatField(null=True)),
                ('abdominal', models.FloatField(null=True)),
                ('supra_iliaca', models.FloatField(null=True)),
                ('coxa', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
