# Generated by Django 5.2.5 on 2025-10-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
